export const countriesData = [
  {
    name: 'Switzerland',
    code: 'CHE',
    capital: ['Bern'],
    region: 'Europe',
    subregion: 'Western Europe',
    population: 8654622,
    flags: {
      png: 'https://flagcdn.com/w320/ch.png',
      svg: 'https://flagcdn.com/ch.svg',
    },
    languages: [
      { code: 'deu', name: 'German' },
      { code: 'fra', name: 'French' },
      { code: 'ita', name: 'Italian' },
      { code: 'roh', name: 'Romansh' },
    ],
    currencies: [{ code: 'CHF', name: 'Swiss franc', symbol: 'Fr' }],
  },
  {
    name: 'United States',
    code: 'USA',
    capital: ['Washington, D.C.'],
    region: 'Americas',
    subregion: 'North America',
    population: 329484123,
    flags: {
      png: 'https://flagcdn.com/w320/us.png',
      svg: 'https://flagcdn.com/us.svg',
    },
    languages: [{ code: 'eng', name: 'English' }],
    currencies: [{ code: 'USD', name: 'United States dollar', symbol: '$' }],
  },
  {
    name: 'Japan',
    code: 'JPN',
    capital: ['Tokyo'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 125836021,
    flags: {
      png: 'https://flagcdn.com/w320/jp.png',
      svg: 'https://flagcdn.com/jp.svg',
    },
    languages: [{ code: 'jpn', name: 'Japanese' }],
    currencies: [{ code: 'JPY', name: 'Japanese yen', symbol: '¥' }],
  },
  {
    name: 'Brazil',
    code: 'BRA',
    capital: ['Brasília'],
    region: 'Americas',
    subregion: 'South America',
    population: 212559409,
    flags: {
      png: 'https://flagcdn.com/w320/br.png',
      svg: 'https://flagcdn.com/br.svg',
    },
    languages: [{ code: 'por', name: 'Portuguese' }],
    currencies: [{ code: 'BRL', name: 'Brazilian real', symbol: 'R$' }],
  },
  {
    name: 'South Africa',
    code: 'ZAF',
    capital: ['Pretoria', 'Cape Town', 'Bloemfontein'],
    region: 'Africa',
    subregion: 'Southern Africa',
    population: 59308690,
    flags: {
      png: 'https://flagcdn.com/w320/za.png',
      svg: 'https://flagcdn.com/za.svg',
    },
    languages: [
      { code: 'afr', name: 'Afrikaans' },
      { code: 'eng', name: 'English' },
      { code: 'nbl', name: 'Southern Ndebele' },
      { code: 'nso', name: 'Northern Sotho' },
      { code: 'sot', name: 'Southern Sotho' },
      { code: 'ssw', name: 'Swati' },
      { code: 'tsn', name: 'Tswana' },
      { code: 'tso', name: 'Tsonga' },
      { code: 'ven', name: 'Venda' },
      { code: 'xho', name: 'Xhosa' },
      { code: 'zul', name: 'Zulu' },
    ],
    currencies: [{ code: 'ZAR', name: 'South African rand', symbol: 'R' }],
  },
  {
    name: 'Australia',
    code: 'AUS',
    capital: ['Canberra'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    population: 25687041,
    flags: {
      png: 'https://flagcdn.com/w320/au.png',
      svg: 'https://flagcdn.com/au.svg',
    },
    languages: [{ code: 'eng', name: 'English' }],
    currencies: [{ code: 'AUD', name: 'Australian dollar', symbol: '$' }],
  },
  {
    name: 'India',
    code: 'IND',
    capital: ['New Delhi'],
    region: 'Asia',
    subregion: 'Southern Asia',
    population: 1380004385,
    flags: {
      png: 'https://flagcdn.com/w320/in.png',
      svg: 'https://flagcdn.com/in.svg',
    },
    languages: [
      { code: 'hin', name: 'Hindi' },
      { code: 'eng', name: 'English' },
    ],
    currencies: [{ code: 'INR', name: 'Indian rupee', symbol: '₹' }],
  },
  {
    name: 'Canada',
    code: 'CAN',
    capital: ['Ottawa'],
    region: 'Americas',
    subregion: 'North America',
    population: 38005238,
    flags: {
      png: 'https://flagcdn.com/w320/ca.png',
      svg: 'https://flagcdn.com/ca.svg',
    },
    languages: [
      { code: 'eng', name: 'English' },
      { code: 'fra', name: 'French' },
    ],
    currencies: [{ code: 'CAD', name: 'Canadian dollar', symbol: '$' }],
  },
  {
    name: 'Egypt',
    code: 'EGY',
    capital: ['Cairo'],
    region: 'Africa',
    subregion: 'Northern Africa',
    population: 102334403,
    flags: {
      png: 'https://flagcdn.com/w320/eg.png',
      svg: 'https://flagcdn.com/eg.svg',
    },
    languages: [{ code: 'ara', name: 'Arabic' }],
    currencies: [{ code: 'EGP', name: 'Egyptian pound', symbol: '£' }],
  },
  {
    name: 'Germany',
    code: 'DEU',
    capital: ['Berlin'],
    region: 'Europe',
    subregion: 'Western Europe',
    population: 83240525,
    flags: {
      png: 'https://flagcdn.com/w320/de.png',
      svg: 'https://flagcdn.com/de.svg',
    },
    languages: [{ code: 'deu', name: 'German' }],
    currencies: [{ code: 'EUR', name: 'Euro', symbol: '€' }],
  },
  {
    name: 'Mexico',
    code: 'MEX',
    capital: ['Mexico City'],
    region: 'Americas',
    subregion: 'North America',
    population: 128932753,
    flags: {
      png: 'https://flagcdn.com/w320/mx.png',
      svg: 'https://flagcdn.com/mx.svg',
    },
    languages: [{ code: 'spa', name: 'Spanish' }],
    currencies: [{ code: 'MXN', name: 'Mexican peso', symbol: '$' }],
  },
  {
    name: 'France',
    code: 'FRA',
    capital: ['Paris'],
    region: 'Europe',
    subregion: 'Western Europe',
    population: 67391582,
    flags: {
      png: 'https://flagcdn.com/w320/fr.png',
      svg: 'https://flagcdn.com/fr.svg',
    },
    languages: [{ code: 'fra', name: 'French' }],
    currencies: [{ code: 'EUR', name: 'Euro', symbol: '€' }],
  },
  {
    name: 'China',
    code: 'CHN',
    capital: ['Beijing'],
    region: 'Asia',
    subregion: 'Eastern Asia',
    population: 1402112000,
    flags: {
      png: 'https://flagcdn.com/w320/cn.png',
      svg: 'https://flagcdn.com/cn.svg',
    },
    languages: [{ code: 'zho', name: 'Chinese' }],
    currencies: [{ code: 'CNY', name: 'Chinese yuan', symbol: '¥' }],
  },
  {
    name: 'United Kingdom',
    code: 'GBR',
    capital: ['London'],
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 67215293,
    flags: {
      png: 'https://flagcdn.com/w320/gb.png',
      svg: 'https://flagcdn.com/gb.svg',
    },
    languages: [{ code: 'eng', name: 'English' }],
    currencies: [{ code: 'GBP', name: 'British pound', symbol: '£' }],
  },
  {
    name: 'Russia',
    code: 'RUS',
    capital: ['Moscow'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 144104080,
    flags: {
      png: 'https://flagcdn.com/w320/ru.png',
      svg: 'https://flagcdn.com/ru.svg',
    },
    languages: [{ code: 'rus', name: 'Russian' }],
    currencies: [{ code: 'RUB', name: 'Russian ruble', symbol: '₽' }],
  },
  {
    name: 'Nigeria',
    code: 'NGA',
    capital: ['Abuja'],
    region: 'Africa',
    subregion: 'Western Africa',
    population: 206139587,
    flags: {
      png: 'https://flagcdn.com/w320/ng.png',
      svg: 'https://flagcdn.com/ng.svg',
    },
    languages: [{ code: 'eng', name: 'English' }],
    currencies: [{ code: 'NGN', name: 'Nigerian naira', symbol: '₦' }],
  },
  {
    name: 'Spain',
    code: 'ESP',
    capital: ['Madrid'],
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 47351567,
    flags: {
      png: 'https://flagcdn.com/w320/es.png',
      svg: 'https://flagcdn.com/es.svg',
    },
    languages: [{ code: 'spa', name: 'Spanish' }],
    currencies: [{ code: 'EUR', name: 'Euro', symbol: '€' }],
  },
  {
    name: 'Italy',
    code: 'ITA',
    capital: ['Rome'],
    region: 'Europe',
    subregion: 'Southern Europe',
    population: 59554023,
    flags: {
      png: 'https://flagcdn.com/w320/it.png',
      svg: 'https://flagcdn.com/it.svg',
    },
    languages: [{ code: 'ita', name: 'Italian' }],
    currencies: [{ code: 'EUR', name: 'Euro', symbol: '€' }],
  },
  {
    name: 'Thailand',
    code: 'THA',
    capital: ['Bangkok'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 69799978,
    flags: {
      png: 'https://flagcdn.com/w320/th.png',
      svg: 'https://flagcdn.com/th.svg',
    },
    languages: [{ code: 'tha', name: 'Thai' }],
    currencies: [{ code: 'THB', name: 'Thai baht', symbol: '฿' }],
  },
  {
    name: 'Argentina',
    code: 'ARG',
    capital: ['Buenos Aires'],
    region: 'Americas',
    subregion: 'South America',
    population: 45376763,
    flags: {
      png: 'https://flagcdn.com/w320/ar.png',
      svg: 'https://flagcdn.com/ar.svg',
    },
    languages: [{ code: 'spa', name: 'Spanish' }],
    currencies: [{ code: 'ARS', name: 'Argentine peso', symbol: '$' }],
  },
  {
    name: 'Sweden',
    code: 'SWE',
    capital: ['Stockholm'],
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 10353442,
    flags: {
      png: 'https://flagcdn.com/w320/se.png',
      svg: 'https://flagcdn.com/se.svg',
    },
    languages: [{ code: 'swe', name: 'Swedish' }],
    currencies: [{ code: 'SEK', name: 'Swedish krona', symbol: 'kr' }],
  },
  {
    name: 'Turkey',
    code: 'TUR',
    capital: ['Ankara'],
    region: 'Asia',
    subregion: 'Western Asia',
    population: 84339067,
    flags: {
      png: 'https://flagcdn.com/w320/tr.png',
      svg: 'https://flagcdn.com/tr.svg',
    },
    languages: [{ code: 'tur', name: 'Turkish' }],
    currencies: [{ code: 'TRY', name: 'Turkish lira', symbol: '₺' }],
  },
  {
    name: 'Indonesia',
    code: 'IDN',
    capital: ['Jakarta'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 273523621,
    flags: {
      png: 'https://flagcdn.com/w320/id.png',
      svg: 'https://flagcdn.com/id.svg',
    },
    languages: [{ code: 'ind', name: 'Indonesian' }],
    currencies: [{ code: 'IDR', name: 'Indonesian rupiah', symbol: 'Rp' }],
  },
  {
    name: 'New Zealand',
    code: 'NZL',
    capital: ['Wellington'],
    region: 'Oceania',
    subregion: 'Australia and New Zealand',
    population: 5084300,
    flags: {
      png: 'https://flagcdn.com/w320/nz.png',
      svg: 'https://flagcdn.com/nz.svg',
    },
    languages: [
      { code: 'eng', name: 'English' },
      { code: 'mri', name: 'Māori' },
      { code: 'nzs', name: 'New Zealand Sign Language' },
    ],
    currencies: [{ code: 'NZD', name: 'New Zealand dollar', symbol: '$' }],
  },
  {
    name: 'Saudi Arabia',
    code: 'SAU',
    capital: ['Riyadh'],
    region: 'Asia',
    subregion: 'Western Asia',
    population: 34813867,
    flags: {
      png: 'https://flagcdn.com/w320/sa.png',
      svg: 'https://flagcdn.com/sa.svg',
    },
    languages: [{ code: 'ara', name: 'Arabic' }],
    currencies: [{ code: 'SAR', name: 'Saudi riyal', symbol: 'ر.س' }],
  },
  {
    name: 'Poland',
    code: 'POL',
    capital: ['Warsaw'],
    region: 'Europe',
    subregion: 'Central Europe',
    population: 37950802,
    flags: {
      png: 'https://flagcdn.com/w320/pl.png',
      svg: 'https://flagcdn.com/pl.svg',
    },
    languages: [{ code: 'pol', name: 'Polish' }],
    currencies: [{ code: 'PLN', name: 'Polish złoty', symbol: 'zł' }],
  },
  {
    name: 'Vietnam',
    code: 'VNM',
    capital: ['Hanoi'],
    region: 'Asia',
    subregion: 'South-Eastern Asia',
    population: 97338583,
    flags: {
      png: 'https://flagcdn.com/w320/vn.png',
      svg: 'https://flagcdn.com/vn.svg',
    },
    languages: [{ code: 'vie', name: 'Vietnamese' }],
    currencies: [{ code: 'VND', name: 'Vietnamese đồng', symbol: '₫' }],
  },
  {
    name: 'Ukraine',
    code: 'UKR',
    capital: ['Kyiv'],
    region: 'Europe',
    subregion: 'Eastern Europe',
    population: 44134693,
    flags: {
      png: 'https://flagcdn.com/w320/ua.png',
      svg: 'https://flagcdn.com/ua.svg',
    },
    languages: [{ code: 'ukr', name: 'Ukrainian' }],
    currencies: [{ code: 'UAH', name: 'Ukrainian hryvnia', symbol: '₴' }],
  },
  {
    name: 'Netherlands',
    code: 'NLD',
    capital: ['Amsterdam'],
    region: 'Europe',
    subregion: 'Western Europe',
    population: 16655799,
    flags: {
      png: 'https://flagcdn.com/w320/nl.png',
      svg: 'https://flagcdn.com/nl.svg',
    },
    languages: [{ code: 'nld', name: 'Dutch' }],
    currencies: [{ code: 'EUR', name: 'Euro', symbol: '€' }],
  },
  {
    name: 'Colombia',
    code: 'COL',
    capital: ['Bogotá'],
    region: 'Americas',
    subregion: 'South America',
    population: 50882884,
    flags: {
      png: 'https://flagcdn.com/w320/co.png',
      svg: 'https://flagcdn.com/co.svg',
    },
    languages: [{ code: 'spa', name: 'Spanish' }],
    currencies: [{ code: 'COP', name: 'Colombian peso', symbol: '$' }],
  },
  {
    name: 'Ireland',
    code: 'IRL',
    capital: ['Dublin'],
    region: 'Europe',
    subregion: 'Northern Europe',
    population: 4994724,
    flags: {
      png: 'https://flagcdn.com/w320/ie.png',
      svg: 'https://flagcdn.com/ie.svg',
    },
    languages: [
      { code: 'eng', name: 'English' },
      { code: 'gle', name: 'Irish' },
    ],
    currencies: [{ code: 'EUR', name: 'Euro', symbol: '€' }],
  },
];
